config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :edit, :show, :index]
  resources :appointments, only: [:new, :show, :index, :create]
  resources :dogs
  resources :reviews
  patch "/sessions/page_view_reset", to: "sessions#page_view_reset", as: "reset_session";
  delete "/sessions/logout", to: "sessions#logout", as: "logout"
  get "/", to: "sessions#new", as: "new_login"
  post "/sessions", to: "sessions#create", as: "login"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :match

  # def appointment_datetime=(appointment_datetime)
  #   self.appointment = Appointment.find_or_create_by(appointment_datetime: appointment_datetime)
  # end 

  # def appointment_datetime
  #   self.appointment ? self.appointment.appointment_datetime : nil
  # end 
  
end

app/models/dog.rb
class Dog < ApplicationRecord
  has_many :matches
  has_many :users, through: :matches
  has_many :appointments, through: :matches 
  has_many :reviews, through: :matches

  validates :name, uniqueness: :true
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :user
  belongs_to :dog
  has_many :reviews
  has_many :appointments
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :match
end

app/models/user.rb
class User < ApplicationRecord
  has_many :matches
  has_many :dogs, through: :matches
  has_many :reviews, through: :matches
  has_many :appointments, through: :matches
  has_secure_password 

  def password=(secret)
    hash_pass = BCrypt::Password.create(secret)
    self.password_digest = hash_pass
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :get_user
  before_action :auth_user

  def get_user
    @current_user = User.find_by(id: session[:user_id])
  end 

  def auth_user
    if @current_user

    else 
      redirect_to new_user_path
    end 
  end 
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
    @appointments = Appointment.all
  end 

  def show
    @appointment = Appointment.find(params[:id])
  end 

  def new
    @appointment = Appointment.new 
  end 

  def create 
    @appointment = Appointment.new(appointment_params)
    @match = Match.create(user_id: @current_user.id, dog_id: params[:match][:dog_id])
    @appointment.match_id = @match.id
    if @appointment.valid?
      @appointment.save
      redirect_to @appointment
    else 
      render :new
    end 
  end 

  private
  def appointment_params
    params.require(:appointment).permit(:match_id, :description, :appointment_datetime)
  end 


end 

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.all
  end
  
  def show
    @dog = Dog.find(params[:id])
  end

  def new
    @dog = Dog.new
  end

  def create
    @dog = Dog.create(dog_params)
    if @dog.persisted?
      redirect_to @dog
    else
      render :new
    end
  end

  def edit
    @dog = Dog.create(dog_params)
    if @dog.persisted?
      redirect_to dog
    else
      render :new
    end
  end


  private
  def dog_params
    params.require(:dog).permit(:name, :breed, :size, :about, :img_url)
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
    @matches = Match.all
  end 

  def show
    @match = Match.find(params[:id])
  end 

  def new
    @match = Match.new 
  end 

  def create 
    @match = Match.new(match_params)
    if @match.save
      redirect_to @match
    else 
      render :new
    end 
  end 

  private
  def match_params
    params.require(:match).permit(:user_id, :dog_id)
  end 

end 

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end 

  def show
    @review = Review.find(params [:id])
  end 

  def new
    @review = Review.new
  end 

  def create
    @review = Review.create(review_params)
    if @review.valid?
      @review.save
      redirect_to @review.user
    else 
      render :new
    end 
  end

  private 
  def review_params
      params.require(:review).permit(:match_id, :appointment_id, :dog_review, :dog_rating)
  end 
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :auth_user, only: [:new, :create]

  def logout
    # session[:id] = nil
    session.delete(:user_id)
  end 

  def new
    
  end 

  def create
    user = User.find_by(username: params[:session][:username])

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user
    else 
      flash[:errors] = "Username or Password is Incorrect"
      redirect_to new_login_path
    end 

  end 
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :auth_user, only: [:new, :create]
  
  def index
    @users = User.all
  end 

  def new
    @user = User.new
  end 

  def show
    @user = User.find(params[:id])

    if @user == @current_user
      render :show
    else 
      flash[:error] = "can only view your own profile page"
      redirect_to user_path(@current_user)
    end
  end

  def create
      @user = User.create(user_params)
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to @user
    else 
      flash[:user_errors] = user.errors.full_messages
      
      redirect_to new_user_path
    end 
  end 

  def edit
    @user = User.find(params[:id])
  end 

  def destroy
    @user = User.find(params [:id])
    @user.destroy
    flash[:notice] = "User deleted"
    redirect_to users_path
  end 

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end 

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
  end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/appointments/index.html.erb
<h1> All Appointments </h1>
<ul>
<% @appointments.each do |appointment| %>
  <li><%= link_to appointment.description, appointment_path(appointment.id) %> - 
  <%= appointment.appointment_datetime.strftime("%B %d, %Y") %>
  <br>
  <% end %>
</ul>

app/views/appointments/new.html.erb
<!DOCTYPE html>
<html lang="en">
<p></p>
<div class="new-app">
<h1> New Appointment </h1>
<p> <b>Let's set a date! Here are your puppy pals: </b></p>
<br>
<p><%= form_for @appointment do |f| %></p>
<p><%= f.label :description %></p>
<p><%= f.text_area :description %></p>
<p><%= f.label :appointment_datetime %></p>
<p><%= f.date_select :appointment_datetime %></p>
<p><%= f.label :dog %></p>
<p><%= collection_select :match, :dog_id, Dog.all, :id, :name %></p>
<p><%= f.submit %></p>
<%end%>
</div>

app/views/appointments/show.html.erb
<h2> You've scheduled an appointment with: </h2>
<ul>
  <li>Name: <%= @appointment.match.dog.name%>
  <li>On: <%= @appointment.appointment_datetime.strftime("%B %d, %Y")%>
  <li>For: <%= @appointment.description %>
  <li><%= link_to "Write a review for this appointment", new_review_path %> </li>
  <li><%= link_to "See all of your appointments", appointments_path %> </li>
  <br>
  <%= image_tag @appointment.match.dog.img_url %></h2>
</ul>

app/views/dogs/index.html.erb
<h1> Our pups: </h1>
<ul>
  <% @dogs.each do |dog| %>
    <li><%= link_to dog.name, dog %></li>
  <% end %>
</ul>
<p><%= link_to "Add A New Dog", new_dog_path %></p> 

app/views/dogs/new.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
  <p><%= error %></p>
  <% end %>
<% end %>
<div class="add-dog">
<h1>Add a new dog!</h1>
<%= form_for @dog do |f| %>
  <p><%= f.label :name %></p>
  <p><%= f.text_field :name %></p>
  <p><%= f.label :breed %></p>
  <p><%= f.text_field :breed %></p>
  <p><%= f.label :size %></p>
  <p><%= f.text_field :size %></p>
  <p><%= f.label :about %></p>
  <p><%= f.text_field :about %></p>
  <p><%= f.label :img_url %></p>
  <p><%= f.text_field :img_url %></p>
  <p><%= f.submit %></p>
  <%end%>
</div>

app/views/dogs/show.html.erb
<h1><%= @dog.name %></h1>

<ul>
    <li>Name: <strong><%= @dog.name%></strong></li>
    <li>Breed: <%= @dog.breed %></li>
    <li>Size: <%= @dog.size %></li>
    <li>About: <%= @dog.about %></li>
    <h3> Check out what folks say about me: </h3>
<ul>
  <% @dog.reviews.each do |r| %>
    <li>Review: <%= link_to r.dog_review, reviews_path(@dog) %> Rating:  <%= r.dog_rating %> out of 5
    <br>
    <br>
  <% end%>
  <%= link_to "Make an appointment with this pup", new_appointment_path %>
  <br>
  <br>
</ul>
    <%= image_tag @dog.img_url %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Puppy Pals!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div>
      <ul class="nav navbar-nav navbar-light bg-light navbar-right">
        <% if @current_user %>
          <li class='right'> Welcome <strong> <%=  @current_user.username %></strong></li>                    
          <li class='right'><%= link_to "Log-Out", logout_path, method: :delete %></li>
          <li><%= link_to 'User Home', user_path(@current_user) %></li>
          <li><%= link_to 'Book a New Session', new_appointment_path %></li>
          <li><%= link_to 'Write a New Review', new_review_path %></li>
          <li><%= link_to 'See all the Dogs', dogs_path %></li>
        <% else %>
          <li class='right'><%= link_to 'Sign-up', new_user_path %></li>
          <li class='right'><%= link_to 'Login', new_login_path %></li>
          <li class='right'><%= link_to 'See all the dogs', dogs_path %></li>
        <% end %>
      </ul>
    <%= yield %>
    </nav>
  </div>
</html>

app/views/matches/new.html.erb
<h1> Your New Puppy Pal </h1>

app/views/reviews/edit.html.erb
<h1> Edit Review </h1>

<h2> Let us know how its going with your pup: </h2>


<%= form_for @review do |f| %>

<%= f.label :appointment %>
<%= collection_select :appointment, :appointment_id, Appointment.all, :id, :description %>

<%= f.label :match %>
<%= collection_select :match, :match_id, Dog.all, :id, :name %>

<%= f.label "Review" %>
<%= f.text_area :dog_review %>

<%= f.label "Rating" %>
<%= f.number_field :dog_rating, within: 1..5 %>

<%= f.submit %>
<%end%>

app/views/reviews/index.html.erb
<h1> Reviews </h1>

<ul>
  <% @reviews.each do |review| %>
    <li> <strong> <%= review.match.dog.name %> </strong> 
    <%= review.dog_rating  %> - <%= review.dog_review %> </li>
  <% end %>
</ul>
<p><%= link_to "Write a New Review", new_review_path %></p> 
    

app/views/reviews/new.html.erb
<h1> New Review </h1>

<h2> Let us know how its going with your pup: </h2>
<br>

<%= form_for @review do |f| %>

<p><%= f.label :appointment %></p>
<p><%= collection_select :appointment, :appointment_id, Appointment.all, :id, :description %></p>
<p><%= f.label :match %></p>
<p><%= collection_select :match, :match_id, Dog.all, :id, :name %></p>
<p><%= f.label "Review" %></p>
<p><%= f.text_area :dog_review %></p>
<p><%= f.label "Rating" %></p>
<p><%= f.number_field :dog_rating, within: 1..5 %></p>
<p></p><%= f.submit %>
<%end%>

app/views/reviews/show.html.erb
<h2> Here's your review </h2>

<h1><%= @review.dog_rating %></h1>
<% @review.match do |match| %>
    <li>
    <%= link_to "Review", review_path(review) %>
    </li>
<%end%>

app/views/users/new.html.erb
<h1> Sign up for Puppy Pals! </h1>

<% if flash[:user_errors] %>
  <% flash[:user_errors].each do |error| %>
    <p style='color: red;'><%= error %></p>
  <% end %>
<% end %>
<body>
<%= form_for @user do |f| %>
<%= f.label :username %>
<%= f.text_field :username %>
<br/>
<%= f.label :password %>
<%= f.text_field :password %>
<br/>
<%= f.submit %>
<%end%>
</body>

app/views/users/show.html.erb
<h1> Welcome <%= @user.username %>!</h1>
<h3> Here are your puppy pals: </h3>
<ul>
  <% @user.matches.each do |m| %>
    <%= link_to m.dog.name, dog_path%><br>
  <%end %>
<br>

<li><%= link_to 'Write a New Review', new_review_path %></li>
  
  <br>
</ul>
<h3> Here are your appointments: </h3>
<ul>
  <%= @user.appointments.each do |a| %>
    <li><%= link_to a.description, appointment_path %> with <strong> <%= a.match.dog.name %> </strong> - <%= a.appointment_datetime.strftime("%B %d, %Y") %> </li>
    <br>
  <% end %>
</ul>